In [1]:
import numpy as np

x = np.array([1, 2, 3], dtype = np.float32) # 1 byte = 8 bits, 4 bytes = 32 bits

x, x.itemsize

(array([1., 2., 3.], dtype=float32), 4)

In [2]:
np.sin(x), np.tanh(x)

(array([0.841471 , 0.9092974, 0.14112  ], dtype=float32),
 array([0.7615942, 0.9640276, 0.9950548], dtype=float32))

In [6]:
x = np.ones((3, 3))
# add one dim
y = x[:, [0, 1, 2, 2]] # then y has independent memory area

# however, if z is generated by slicing x
z = x[:2, :2] # then z is just a view of x, so change the elements in x also change the elements in z

x[1, 1] = 9

y, z

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[1., 1.],
        [1., 9.]]))

In [13]:
# Explicit force a copy
x = np.ones((3, 3))
z = x[:2, :2].copy() # z becomes independent

x[1, 1] = 9

x, z

(array([[1., 1., 1.],
        [1., 9., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.]]))

In [14]:
x.flags, "\n", z.flags # "flags" can help

(  C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : True
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False,
 '\n',
   C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : True
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False)